services:
    redis:
        image: "redis/redis-stack:latest"
        ports:
            - '6379:6379'
            - '8001:8001'
    rabbitmq:
        image: "rabbitmq:4-management"
        ports:
            - '5672:5672'
            - '15672:15672'
