apiVersion: v1
kind: Pod
metadata:
  name: backend-test
spec:
  containers:
  - image: europe-west1-docker.pkg.dev/polytech-dijon/polytech-dijon/backend-2024:davin-druhet
    name: backend-test
    ports:
    - containerPort: 5000
      name: http
      protocol: TCP