apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  selector:
    app: backend
  env:
  - name: REDIS_HOST
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: REDIS_PORT
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace
  - name: RABBIT_HOST
    valueFrom:
      fieldRef:
        fieldPath: metadata.name
  - name: RABBIT_PORT
    valueFrom:
      fieldRef:
        fieldPath: metadata.namespace